### ISSUE TITLE
deprecation spam

### ISSUE THREAD

**Issue by sakulstra** [accounts-js/accounts#854]
We're currently getting spammed by
```
(node:8221) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:8221) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:8221) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```
warnings... which i think are related to this package. Will have a look myself when i find some time, but thought it might make sense to post my findings here in case someone wants to have a look.

https://github.com/nodejs/node/issues/23203#issuecomment-491963401

**Comment by pradel** [comment]
Thanks for reporting the issue, looks like it's coming from this file `packages/password/src/utils/encryption.ts`.
Replacing `import * as crypto from 'crypto';` with `import { createHash } from 'crypto';` should fix the warnings. Happy to accept a pr with the fix 👍

**Comment by acomito** [comment]
Is this in the latest npm release? I just upgraded but still seeing this
```
(node:2816) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:2816) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```

**Comment by pradel** [comment]
@acomito I still didn't publish it, will create a new release this week
